---
- name: IOS modules playbook example
  hosts: webserver
  become: yes
  tasks:
    - name: jst for check
      debug:
        msg: "hello"
    - name: run show version on remote devices
      ios_command:
        commands: show version
    #   register: command
    #   debug:
    #     msg: command