---
- name: IOS modules playbook example
  hosts: webserver
  become: yes
  tasks:
    - name: run show version on remote devices
      ios_command:
        commands: show version
    #   register: command
    #   debug:
    #     msg: command