---
- name: loops example playbook
  hosts: webserver
  become: yes
  tasks:
    - name: file creation
      digital_ocean:
        name: "{{ item }}"
        state: present
        loop:
        - file3.txt
        - file4.txt
    # - name: delete multiple files from location
    #   file:
    #     path:
    #   state: absent