---
- name: loops example playbook
  hosts: webserver
  become: yes
  tasks:
    - name: file creation
      file:
        path: "{{ item }}"
        state: touch
      with_items:
        - file3.txt
        - file4.txt
    - name: delete multiple files from a location
      file:
         path: "{{ item }}"
         state: absent
      loop:
        - file3.txt
        - file2.txt